feat: Add error context when lowering hugrs to LLVM (#2869)
Because 
```
thread 'emit::test::test_fns::tail_loop_exec::case_1' (101506913) panicked at hugr-llvm/src/test.rs:173:92:
called `Result::unwrap()` on an `Err` value: Unknown type: int(6)
```
is a useless error when it happens deeply nested inside some other
workflow.

This PR adds some anyhow contexts, so the error now shows
```
thread 'emit::test::test_fns::tail_loop_exec::case_1' (101503258) panicked at hugr-llvm/src/test.rs:173:92:
called `Result::unwrap()` on an `Err` value: Failed to emit LLVM for function 'main' at node Node(1)

Caused by:
    No mapping found for type: int(6)
```

See https://github.com/Quantinuum/hugr-qir/issues/218 for an example
happening in the wild.