chore(deps-rs): bump the patch group with 4 updates (#2887)
Bumps the patch group with 4 updates:
[capnp](https://github.com/capnproto/capnproto-rust),
[clap](https://github.com/clap-rs/clap),
[pyo3](https://github.com/pyo3/pyo3) and
[cc](https://github.com/rust-lang/cc-rs).

Updates `capnp` from 0.25.0 to 0.25.1
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/2ae271a12b4d7d86cd05214390fadb1d594b754d"><code>2ae271a</code></a>
prepare for capnp-v0.25.1 release</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/370907c7d8c565482e08a3c47666a25a7c28f172"><code>370907c</code></a>
prevent overflow in init_struct_list_pointer</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/9f6a4ee9fa16e3a4384057adf4f34c487422c6ea"><code>9f6a4ee</code></a>
catch some potential overflows on list upgrades</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/08c1c4e33b9fce8a73fba4b0e5f77d27b6d43d8c"><code>08c1c4e</code></a>
fix off-by-one bug in list upgrades</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/e5d0f80ad317d425a16eb5600358e338bc4fe0de"><code>e5d0f80</code></a>
prevent overflow on huge text initialization</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/0b7e6c0cd0bf892da0d8e6beffd9c9c2b7f7f28f"><code>0b7e6c0</code></a>
be extra sure to avoid underflow in NullArean::check_offset</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/90d728e610c54b387c18402580f494efe96625e9"><code>90d728e</code></a>
avoid quickcheck 1.1.0, which pulls in newer version of rand</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/781596246243f401b9e1f1aa66eebff4573d5a5f"><code>7815962</code></a>
prepare for capnp-futures-v0.25.1 release</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/faea11d86e9d8cb6c4646deceeb9c2b6b1437ea4"><code>faea11d</code></a>
[capnp-futures] Error::failed -&gt; PrematureEndOfFile</li>
<li><a
href="https://github.com/capnproto/capnproto-rust/commit/be956d7477f235d226085ffc7c17ebad6f194293"><code>be956d7</code></a>
migrate some straggling tests to the generated_code macro (<a
href="https://redirect.github.com/capnproto/capnproto-rust/issues/617">#617</a>)</li>
<li>See full diff in <a
href="https://github.com/capnproto/capnproto-rust/compare/capnp-v0.25.0...capnp-v0.25.1">compare
view</a></li>
</ul>
</details>
<br />

Updates `clap` from 4.5.58 to 4.5.59
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/clap-rs/clap/releases">clap's
releases</a>.</em></p>
<blockquote>
<h2>v4.5.59</h2>
<h2>[4.5.59] - 2026-02-16</h2>
<h3>Fixes</h3>
<ul>
<li><code>Command::ignore_errors</code> no longer masks help/version on
subcommands</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/clap-rs/clap/blob/master/CHANGELOG.md">clap's
changelog</a>.</em></p>
<blockquote>
<h2>[4.5.59] - 2026-02-16</h2>
<h3>Fixes</h3>
<ul>
<li><code>Command::ignore_errors</code> no longer masks help/version on
subcommands</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/clap-rs/clap/commit/0bb3ad7e12e729be9f152391558689ac4fdd31ec"><code>0bb3ad7</code></a>
chore: Release</li>
<li><a
href="https://github.com/clap-rs/clap/commit/5cb5ce3873a882ba2a7d619864202eadef21fffa"><code>5cb5ce3</code></a>
docs: Update changelog</li>
<li><a
href="https://github.com/clap-rs/clap/commit/245c8ba75a481250a48170f1add11532a7b7fd33"><code>245c8ba</code></a>
Merge pull request <a
href="https://redirect.github.com/clap-rs/clap/issues/6149">#6149</a>
from epage/wrap</li>
<li><a
href="https://github.com/clap-rs/clap/commit/dd17a418a9e6665c98ff6e0ba2a039fd1921988e"><code>dd17a41</code></a>
fix(help): Correctly calculate wrap points with ANSI escape codes</li>
<li><a
href="https://github.com/clap-rs/clap/commit/2cc4e350b9ea8955a9cf229405407426921e7871"><code>2cc4e35</code></a>
test(ui): Avoid override term width</li>
<li><a
href="https://github.com/clap-rs/clap/commit/93e3559b1e4c8c81377f3598f7249b7708f4c379"><code>93e3559</code></a>
refactor(help): Clarify that we're carrying over indentation</li>
<li><a
href="https://github.com/clap-rs/clap/commit/b1c46e633c04f5cb0d819b15f25c1fde1a6e42c4"><code>b1c46e6</code></a>
refactor(help): Clarify var name</li>
<li><a
href="https://github.com/clap-rs/clap/commit/03b9b38df059c1a9a529f295e038f81de295627a"><code>03b9b38</code></a>
test(help): Show styled wrapping behavior</li>
<li><a
href="https://github.com/clap-rs/clap/commit/c9a39a534c3e95926be272765bec48a80e5ea9e7"><code>c9a39a5</code></a>
Merge pull request <a
href="https://redirect.github.com/clap-rs/clap/issues/6146">#6146</a>
from clap-rs/renovate/actions-checkout-5.x</li>
<li><a
href="https://github.com/clap-rs/clap/commit/58599fb7bf865f8ec0a7a021dea8111f5dffe6d2"><code>58599fb</code></a>
chore(deps): Update actions/checkout action to v5</li>
<li>Additional commits viewable in <a
href="https://github.com/clap-rs/clap/compare/clap_complete-v4.5.58...clap_complete-v4.5.59">compare
view</a></li>
</ul>
</details>
<br />

Updates `pyo3` from 0.28.0 to 0.28.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/pyo3/pyo3/releases">pyo3's
releases</a>.</em></p>
<blockquote>
<h2>PyO3 0.28.2</h2>
<p>This patch release contains a soundness fix for subclassing native
types such as <code>PyList</code> with the <code>abi3</code> feature
enabled when targeting a minimum version of Python 3.12 or higher.
(Support for doing such subclassing was newly added in PyO3 0.28.0.)</p>
<p>PyO3 0.28.0 and 0.28.1 will be yanked.</p>
<p>This release also contains a correction to the FFI definition
<code>PyType_GetTypeDataSize</code> and incorrectly-generated
<code>__qualname__</code> on <code>#[pyclass]</code> enum variant types
when using <code>#[pyo3(name = &quot;...&quot;)]</code> option to rename
the enum and/or variant.</p>
<p>Thank you to the following contributors for the improvements:</p>
<p><a
href="https://github.com/davidhewitt"><code>@​davidhewitt</code></a>
<a href="https://github.com/Icxolu"><code>@​Icxolu</code></a>
<a href="https://github.com/ngoldbaum"><code>@​ngoldbaum</code></a></p>
<h2>PyO3 0.28.1</h2>
<p>This patch contains a number of minor compile-time fixes for PyO3
0.28.0.</p>
<p>Thank you to the following contributors for the improvements:</p>
<p><a
href="https://github.com/davidhewitt"><code>@​davidhewitt</code></a>
<a href="https://github.com/funsafemath"><code>@​funsafemath</code></a>
<a href="https://github.com/ngoldbaum"><code>@​ngoldbaum</code></a>
<a href="https://github.com/rara64"><code>@​rara64</code></a>
<a href="https://github.com/tdyas"><code>@​tdyas</code></a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/PyO3/pyo3/blob/v0.28.2/CHANGELOG.md">pyo3's
changelog</a>.</em></p>
<blockquote>
<h2>[0.28.2] - 2026-02-18</h2>
<h3>Fixed</h3>
<ul>
<li>Fix complex enum <code>__qualname__</code> not using python name <a
href="https://redirect.github.com/PyO3/pyo3/pull/5815">#5815</a></li>
<li>Fix FFI definition <code>PyType_GetTypeDataSize</code> (was
incorrectly named <code>PyObject_GetTypeDataSize</code>). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5819">#5819</a></li>
<li>Fix memory corruption when subclassing native types with
<code>abi3</code> feature on Python 3.12+ (newly enabled in PyO3
0.28.0). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5823">#5823</a></li>
</ul>
<h2>[0.28.1] - 2026-02-14</h2>
<h3>Fixed</h3>
<ul>
<li>Fix <code>*args</code> / <code>**kwargs</code> support in<code>
experimental-async</code> feature (regressed in 0.28.0). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5771">#5771</a></li>
<li>Fix <code>clippy::declare_interior_mutable_const</code> warning
inside <code>#[pyclass]</code> generated code on enums. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5772">#5772</a></li>
<li>Fix <code>ambiguous_associated_items</code> compilation error when
deriving <code>FromPyObject</code> or using
<code>#[pyclass(from_py_object)]</code> macro on enums with
<code>Error</code> variant. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5784">#5784</a></li>
<li>Fix <code>__qualname__</code> for complex <code>#[pyclass]</code>
enum variants to include the enum name. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5796">#5796</a></li>
<li>Fix missing <code>std::sync::atomic::Ordering</code> import for
targets without atomic64. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5808">#5808</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/PyO3/pyo3/commit/2b392c8500673520066486f6098cbf2316211ff6"><code>2b392c8</code></a>
release: 0.28.2</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/7e44c1d64d40a12e0bd55c819e3feda5322fc219"><code>7e44c1d</code></a>
fix complex enum <code>__qualname__</code> not using python name (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5815">#5815</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/75abd8602896b350fd8c778e52e0a74b4644ccca"><code>75abd86</code></a>
fix memory corruption when subclassing variable-size types (e.g.
<code>abi3</code> + 3.1...</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/b62c7a278fc14e9afb0d73ab1ded7ba00cda3be2"><code>b62c7a2</code></a>
Fix typo in PyType_GetTypeDataSize bindings (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5819">#5819</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/45f49ff9f50538c5bc2ea2c5045ee58f7270bfad"><code>45f49ff</code></a>
release: 0.28.1</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/56c34d630b8c133b3298ccae601dff2f6d5a9798"><code>56c34d6</code></a>
Document Py_GIL_DISABLED in pyo3-build-config docs (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5810">#5810</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/92bc9efd51f70d72d71223b2d661b7d9cc074ef6"><code>92bc9ef</code></a>
Avoid unused variable warning with a debug Python build (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5811">#5811</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/ca5df1a72d745c27327cddd3726aebda88556614"><code>ca5df1a</code></a>
ci: re-enable <code>list_get_item_unchecked</code> benchmark on
free-threaded build (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5812">#5812</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/413d9b5b0130dd636d250be03d807b6091beab5e"><code>413d9b5</code></a>
Fix missing <code>std::sync::atomic::Ordering</code> import for targets
without atomic64...</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/1c764cdc377d41f7117524fd9ecb311a81a2029c"><code>1c764cd</code></a>
docs: improve messaging around <code>#[pyclass(from_py_object)]</code>
change (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5798">#5798</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/pyo3/pyo3/compare/v0.28.0...v0.28.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `cc` from 1.2.55 to 1.2.56
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rust-lang/cc-rs/releases">cc's
releases</a>.</em></p>
<blockquote>
<h2>cc-v1.2.56</h2>
<h3>Other</h3>
<ul>
<li>Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1676">#1676</a>)</li>
<li>Fix <code>clang-cl</code> target when cross-compiling (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1670">#1670</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rust-lang/cc-rs/blob/main/CHANGELOG.md">cc's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/rust-lang/cc-rs/compare/cc-v1.2.55...cc-v1.2.56">1.2.56</a>
- 2026-02-13</h2>
<h3>Other</h3>
<ul>
<li>Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1676">#1676</a>)</li>
<li>Fix <code>clang-cl</code> target when cross-compiling (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1670">#1670</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/709c27f9aa188db973958c332f2c3e047c732fdf"><code>709c27f</code></a>
chore(cc): release v1.2.56 (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1677">#1677</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/743f2c9f7f8088668922f4d3ff37d5bf4cce0d3a"><code>743f2c9</code></a>
Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1676">#1676</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/9eda981969881ed8ff27a5c693f4875cbafe0263"><code>9eda981</code></a>
Fix <code>clang-cl</code> target when cross-compiling (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1670">#1670</a>)</li>
<li>See full diff in <a
href="https://github.com/rust-lang/cc-rs/compare/cc-v1.2.55...cc-v1.2.56">compare
view</a></li>
</ul>
</details>
<br />

<details>
<summary>Most Recent Ignore Conditions Applied to This Pull
Request</summary>

| Dependency Name | Ignore Conditions |
| --- | --- |
| pyo3 | [>= 0.20.a, < 0.21] |
</details>


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>